name: 'proofifi'
services:
  frontend:
    build:
      context: ../../frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_HOST="http://localhost:3000"
      - NEXT_PUBLIC_PRIVY_APP_ID=
      - NEXT_PUBLIC_PINATA_JWT=
      - NEXT_PUBLIC_PINATA_GATEWAY_URL=
      - NEXT_PUBLIC_RPC_URL_BASE_SEPOLIA=
      - NEXT_PUBLIC_BACKEND_URL="http://backend:3001"
      - NEXT_PUBLIC_ERC721_ADDRESS=
      - NEXT_PUBLIC_ERC721_OWNER=
      - NEXT_PUBLIC_ERC721_OWNER_PK=
    hostname: frontend
    container_name: frontend
    depends_on:
      - backend
    networks:
      - proofifi-network

  backend:
    build:
      context: ../../backend
    ports:
      - 3001:3001
    environment:
      - DATABASE_URL=
    hostname: backend
    container_name: backend
    networks:
      - proofifi-network 

networks:
  proofifi-network:
    driver: bridge